# Basic Information 
title: Wenxuan Zhang
position: PhD Student
affiliation: KAUST
affiliation_link: https://wx-zhang.github.io/
affiliation_logo: ./assets/img/kaust_logo.svg
email: wenxuan.zhang@kaust.edu.sa

# Search Engine Optimization (SEO)
keywords: wenxuan zhang, wenxuan, 
canonical: https://wx-zhang.github.io/
description: Wenxuan Zhang is a PhD student at King Abdullah University, Saudi Arabia. Her research lies in Continual Learning, Foundation models, and Alignment.

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com/citations?user=GzBuFCAAAAAJ&hl=en
cv_link: ./assets/pdf/cv_2023.pdf
github_link: https://github.com/wx-zhang
linkedin: https://www.linkedin.com/in/wenxuan-zhang-0960b11b8/
twitter: 

# Images 
avatar: ./assets/img/profile_pic.webp
favicon: ./assets/img/kaust_favicon.png
favicon_dark: ./assets/img/kaust_favicon.png

# Footnotes
footnote: Adapted from the Minimal Light theme by Yaoyao Liu.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
